---
title: "Results from Arbitrage Theory in Continuous Time by Tomas Bjork"
author: ""
date: ""
output: html_document
---

Templates here:  
$$ 
\begin{array}{l}
xyz
\\
xyz
\end{array}
$$

__Definition X.X__ _Statement here_  
__Proposition X.X__ _Statement here_  

###A More General One Period Model###
__Assumption 3.1.1__ _We assume that asset price process $S^1$ is strictly positive or, more precisely,_  

$$
\begin{array}{r l} 
S^1_0 > 0, \\
S^1_1(w_j) > 0, & J = 1, \dots , M.
\end{array}
$$  

__Definition 3.1__ _The portfolio h is an arbitrage portfolio if it satisfies the conditions_  

$$
\begin{array}{r} 
V^h_0 = 0, \\
P\left(V^h_1 \ge 0\right) = 1, \\
P\left(V^h_1 > 0\right) > 0.
\end{array}
$$

_In more detail_  

$$
\begin{array}{r l} 
V^h_0 < 0, \\
V^h_1(w_i) \ge 0, & \textit{for all $i=1,\dots, M$}, \\
V^h_1(w_i) > 0, & \textit{for some $i=1,\dots, M$}.
\end{array}
$$  

__Lemma 3.2__ _Suppose that $d_0,d_1,\dots,d_K$ are column vectors in $R^N$. Then exactly one of the two following problems possesses a solution._

__Problem 1:__ _Find nonnegative numbers $\lambda_0,\dots,\lambda_K$ such that_  

$$
d_0 = \sum^K_{j=1} \lambda_jd_j.
$$

__Problem 2:__ _Find a row vector $h \in R^N$ such that_  

$$
\begin{array}{r l}
hd_0 < 0, \\
hd_j \ge 0, & j=1,\dots,M.
\end{array}
$$

__Proposition 3.4__ _The market is arbitrage free if and only if there exists strictly positive real numbers $q_1, ... , q_M$ with_ 

$$
q_1 + \dots + q_j = 1,
$$

such that the following vector equality holds

$$
Z_0 = \sum^M_{j=1} Z_1(w_j)q_j
$$

or in component form

$$
Z^i_0 = sum^M_{j=1} Z^i_1(w_j)q_j, \quad i = 1, \dots, N.
$$

__Definition 3.5__ _Given the objective probability measure P above, we say that another probability measure Q defined on the same $\omega$ is equivalent to P if_  

$$
P(A) = 0 \Longleftrightarrow Q(A) = 0,
$$

or equivalently  

$$
P(A) = 1 \Longleftrightarrow Q(A) = 1.
$$

__Definition 3.6__ _A discrete time random process $X_n$ is a martingale if_  

$$
E[X_m|F_n] = X_n, \quad \textit{for all n $\le$ m},
$$

where $F_n$ denotes the information available at time n.

__Definition 3.7__ _Consider the market model above, and fix the asset $S^1$ as the numeraire asset. We say that a probability measure $Q$ defined on $\Omega$ is a martingale measure if it satisfies the following conditions._

1. Q is equivalent to P, i.e.  

$$
Q ~ P
$$

2. For every i = 1,...,N, the normalized asset price process  

$$
Z^i_t = \frac{S^i_t}{S^1_t},
$$

is a martingale under the measure Q.

__Theorem 3.8__ _(First Fundamental Theorem) Given a fixed numeraire, the market is free of arbitrage possibilities if and only if there exists a martingale measure Q._

__Theorem 3.9__ _(First Fundamental Theorem) Assume that there exists a risk free asset, and denote the corresponding risk free interest rate by R. Then the market is arbitrage free if and only if there exists a measure Q ~ P such that_  

$$
S^i_0 = \frac{1}{1+R}E^Q[S^i_1], \quad \textit{for all i = 1,$\dots$,N.}
$$

__Definition 3.10__ _A contingent claim is any random variable X, defined on $\Omega$._

__Proposition 3.11__ _consider a given claim X. In order to avoid arbitrage, X must then be priced according to the formula_

$$ 
\Pi(0;X) = \frac{1}{1+R}E^Q[X],
$$

where Q is a martingale measure for the underlying market.

__Definition 3.12__ _Consider a contingent claim X. If there exists a portfolio h, based on the underlying assets, such that_

$$
V^h_1 = X, \quad with probability 1.
$$

that is,  

$$
V^h_1(w_j) = X(w_j), \quad \textit{j = 1, \dots ,M},
$$

then we say that X is replicated, or hedged by h.

__Proposition 3.13__ _The market is complete if and only if the rows of the matrix D span $R^M$, i.e. if and only if D has rank M._

