---
title: "Results from Arbitrage Theory in Continuous Time by Tomas Bjork"
author: ""
date: ""
output: html_document
---

Templates here:  
$$ 
\begin{array}{l}
xyz
\\
xyz
\end{array}
$$

__Definition X.X__ _Statement here_  
__Proposition X.X__ _Statement here_  

###Stochastic integrals###
__Definition 4.1__ _A stochastic process W is called a Wiener process if the following conditions hold._  

1. W(0) = 0.
2. The process W has independent increments, i.e. if $r < s \le t < u$ then $W(u) - W(t)$ and $W(s) - W(r)$ are independent stochastic variables.    
3. For $s < t$ the stochastic variable $W(t) - W(s)$ has the Gaussian distribution $N[0, \sqrt{t-s}]$.  
4. W has continuous trajectories.  

Information  

__Definition 4.2__ _The symbol $F^X_t$ denotes "the information generated by X on the interval [0,t]", or alternatively "what has happened to X over the interval [0,t]". If, based upon observations of the trajectory $\{ X(n); 0 \le s \le t \}$, it is posible to decide whether a given gevent A has occured or not, then we write this as_  

$$
A \in F^X_t,
$$

or say that "A is $F^X_t$ -measureable"  

__Definition 4.3__   

1. We say that the process g belongs to the class $L^2[a,b]$ if the following conditions are satisfied.  

* $\integral^b_a E[g^2(s)] ds < \infinity$.  
* The process g is adapted to the $F^W_t$-filtration.

2. We say that the process g belongs to the class $L^2$ if $g \in L^2[0,t]$ for all t > 0.

__Proposition 4.4__ _Let g be a process satisfying the conditions_  

$$
\begin{array}{c}
\integral^b_a E[g^2(s)]ds < \infinity, \\
\textit{g is adapted to the $F^W_t$-filtration}
\end{array}
$$  

Then the following relations hold

$$
\begin{array}{c}
 \\
 \\
\end{array}
$$